# Generated by Django 2.2.3 on 2019-07-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190723_0445'),
        ('account', '0002_auto_20190722_0034'),
    ]

    operations = [
    ]
