# Generated by Django 2.2.3 on 2019-07-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190723_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_table',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=91),
        ),
    ]
