# Generated by Django 2.2.3 on 2019-08-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190731_1535'),
        ('account', '0003_merge_20190725_2131'),
    ]

    operations = [
    ]
