# Generated by Django 2.2.3 on 2019-08-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_merge_20190725_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_table',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=91),
        ),
    ]
