# Generated by Django 2.2.4 on 2019-08-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190802_1904'),
        ('account', '0004_merge_20190802_1910'),
    ]

    operations = [
    ]
